name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '5 4 * * 2' # once a week on Tuesday

jobs:
  format:
    name: Format
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v1
      - run: CHECK_FORMAT=1 ./format.sh

  legion:
    name: Legion (DEBUG=${{ matrix.debug }}, NETWORKS=${{ matrix.networks }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'macos-11' # FIXME: macOS is broken: https://github.com/StanfordLegion/legion/issues/213
        debug: ['1', '0']
        networks: ['', 'mpi']
    steps:
      - uses: actions/checkout@v1
      - run: ./test.sh
        env:
          DEBUG: ${{ matrix.debug }}
          INSTALL_DEPS: '1'
          SUDO_COMMAND: sudo

  regent:
    name: Regent (DEBUG=${{ matrix.debug }}, NETWORKS=${{ matrix.networks }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04'] # 'macos-11' # FIXME: macOS is broken: https://github.com/StanfordLegion/legion/issues/213
        debug: ['1', '0']
        #networks: ['', 'mpi']
    steps:
      - uses: actions/checkout@v1
      - run: ./test.sh
        env:
          DEBUG: ${{ matrix.debug }}
          USE_REGENT: '1'
          INSTALL_DEPS: '1'
          SUDO_COMMAND: sudo
